export const GET_GAME_SUCCEED = "GET_GAME_SUCCEED";
export const GET_GAME_FAILED = "GET_GAME_FAILED";
export const AUTOPILOT_GAME_SUCCEED = "AUTOPILOT_GAME_SUCCEED";
export const AUTOPILOT_GAME_FAILED = "AUTOPILOT_GAME_FAILED";
export const CHALLENGE_SUCCEED = "CHALLENGE_SUCCEED";
export const CHALLENGE_FAILED = "CHALLENGE_FAILED";
export const SALVO_SUCCEED = "SALVO_SUCCEED";
export const SALVO_FAILED = "SALVO_FAILED";